# SwiftLint Configuration for SwiftSweep
# Matches existing code style: 2-space indentation, 120 char line length

# Paths to include/exclude
included:
  - Sources
  - Tests
excluded:
  - .build
  - Packages
  - Helper

# Opt-in rules (gradually enable more)
opt_in_rules:
  - force_unwrapping
  - fatal_error_message
  - explicit_init
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - explicit_type_interface
  - file_header
  - first_where
  - last_where
  - multiline_function_chains
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# Disabled rules
disabled_rules:
  - identifier_name  # Allow Chinese comments and short names
  - todo  # Allow TODO comments during development
  - line_length  # Handled by custom rule below

# Custom rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level: 2
  function_level: 3

# Naming conventions
type_name:
  min_length: 2
  max_length: 50

# Force cast/try warnings
force_cast: warning
force_try: warning

# Indentation (2 spaces)
indentation: 2

# Trailing whitespace
trailing_whitespace:
  ignores_empty_lines: false
  ignores_comments: false

# Vertical whitespace
vertical_whitespace:
  max_empty_lines: 2

# Custom reporter
reporter: "xcode"
