name: SwiftSweepDevID
options:
  bundleIdPrefix: com.swiftsweep
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

settings:
  DEVELOPMENT_TEAM: 6429YPLDYU
  CODE_SIGN_STYLE: Automatic  # Xcode Cloud 需要自动签名
  # CODE_SIGN_IDENTITY 由 Xcode Cloud 自动管理

packages:
  SwiftSweepAppInventory:
    path: Packages/SwiftSweepAppInventory
  ArgumentParser:
    url: https://github.com/apple/swift-argument-parser
    from: "1.6.0"
  Logging:
    url: https://github.com/apple/swift-log
    from: "1.6.0"

targets:
  SwiftSweepApp:
    type: application
    platform: macOS
    sources:
      - path: Sources/SwiftSweepUI
        type: group
      - path: Sources/SwiftSweepCore
        type: group
      - path: Sources/SwiftSweepCapCutPlugin
        type: group
      - path: Resources/Assets.xcassets
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.swiftsweep.app
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      INFOPLIST_FILE: Resources/Info.plist
      MARKETING_VERSION: "0.4.0"
      CURRENT_PROJECT_VERSION: 4
      SWIFT_VERSION: "5.9"
      # Hardened Runtime (公证要求)
      ENABLE_HARDENED_RUNTIME: YES
    entitlements:
      path: Entitlements/SwiftSweepApp.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.cs.allow-jit: true
        com.apple.security.cs.allow-unsigned-executable-memory: true
        com.apple.security.cs.disable-library-validation: true
    info:
      path: Resources/Info.plist
      properties:
        CFBundleURLTypes:
          - CFBundleURLName: com.swiftsweep.app
            CFBundleURLSchemes:
              - swiftsweep
        LSMinimumSystemVersion: "13.0"
        NSHighResolutionCapable: true
        LSApplicationCategoryType: public.app-category.utilities
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
    dependencies:
      - target: SwiftSweepHelper
        embed: false
        copy:
          destination: executables
          subpath: ../Library/LaunchDaemons
      - package: SwiftSweepAppInventory
        product: SwiftSweepAppInventory
      - package: Logging
        product: Logging
      - sdk: libEndpointSecurity.tbd
    postCompileScripts:
      - name: Bundle Helper Binary and LaunchDaemon plist
        script: |
          APP_DAEMON_DIR="${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/Contents/Library/LaunchDaemons"
          mkdir -p "$APP_DAEMON_DIR"

          HELPER_CANDIDATES=(
            "${BUILT_PRODUCTS_DIR}/SwiftSweepHelper"
            "${TARGET_BUILD_DIR}/SwiftSweepHelper"
          )
          for helper_path in "${HELPER_CANDIDATES[@]}"; do
            if [[ -f "$helper_path" ]]; then
              cp "$helper_path" "$APP_DAEMON_DIR/com.swiftsweep.helper"
              chmod +x "$APP_DAEMON_DIR/com.swiftsweep.helper"
              break
            fi
          done

          if [[ ! -f "$APP_DAEMON_DIR/com.swiftsweep.helper" ]]; then
            echo "warning: SwiftSweepHelper binary was not found in build products"
          fi

          cp "${SRCROOT}/Helper/com.swiftsweep.helper.plist" "$APP_DAEMON_DIR/"
        basedOnDependencyAnalysis: false

  SwiftSweepHelper:
    type: tool
    platform: macOS
    sources:
      - path: Helper
        excludes:
          - "*.plist"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.swiftsweep.helper
      INFOPLIST_FILE: Helper/Info.plist
      SWIFT_VERSION: "5.9"
      SKIP_INSTALL: YES
      # Xcode Cloud 自动管理签名
      ENABLE_HARDENED_RUNTIME: YES
      OTHER_LDFLAGS:
        - "-sectcreate"
        - "__TEXT"
        - "__info_plist"
        - "$(SRCROOT)/Helper/Info.plist"
    info:
      path: Helper/Info.plist

  swiftsweep:
    type: tool
    platform: macOS
    sources:
      - path: Sources/SwiftSweepCLI
        type: group
      - path: Sources/SwiftSweepCore
        type: group
    settings:
      PRODUCT_NAME: swiftsweep
      SWIFT_VERSION: "5.9"
    dependencies:
      - package: ArgumentParser
      - package: Logging
      - sdk: libEndpointSecurity.tbd

schemes:
  SwiftSweepApp:
    build:
      targets:
        SwiftSweepApp: all
        SwiftSweepHelper: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  swiftsweep:
    build:
      targets:
        swiftsweep: all
    run:
      config: Debug


