name: SwiftSweepMAS
options:
  bundleIdPrefix: com.swiftsweep
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

settings:
  DEVELOPMENT_TEAM: 6429YPLDYU
  CODE_SIGN_STYLE: Automatic

packages:
  SwiftSweepAppInventory:
    path: ../Packages/SwiftSweepAppInventory

targets:
  SwiftSweepMAS:
    type: application
    platform: macOS
    sources:
      - path: SwiftSweepMAS
        type: group
      - path: Shared
        type: group
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.swiftsweep.mas
      INFOPLIST_GENERATION_MODE: GeneratedFile
      INFOPLIST_KEY_CFBundleDisplayName: SwiftSweep
      INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
      INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2024 SwiftSweep. All rights reserved."
      MARKETING_VERSION: "1.0.0"
      CURRENT_PROJECT_VERSION: 1
      GENERATE_INFOPLIST_FILE: YES
      CODE_SIGN_ENTITLEMENTS: Entitlements/SwiftSweepMAS.entitlements
      SWIFT_VERSION: "5.9"
    entitlements:
      path: Entitlements/SwiftSweepMAS.entitlements
    info:
      path: SwiftSweepMAS/Info.plist
      properties:
        CFBundleURLTypes:
          - CFBundleURLName: com.swiftsweep.mas
            CFBundleURLSchemes:
              - swiftsweepmas
        LSMinimumSystemVersion: "13.0"
    dependencies:
      - target: FinderSyncExtension
        embed: true
        codeSign: true
      - package: SwiftSweepAppInventory
        product: SwiftSweepAppInventory

  FinderSyncExtension:
    type: app-extension
    platform: macOS
    sources:
      - path: FinderSyncExtension
        type: group
      - path: Shared
        type: group
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.swiftsweep.mas.findersync
      INFOPLIST_GENERATION_MODE: GeneratedFile
      GENERATE_INFOPLIST_FILE: YES
      CODE_SIGN_ENTITLEMENTS: Entitlements/FinderSyncExtension.entitlements
      SWIFT_VERSION: "5.9"
      SKIP_INSTALL: YES
      MARKETING_VERSION: "1.0.0"
      CURRENT_PROJECT_VERSION: 1
      LD_RUNPATH_SEARCH_PATHS:
        - "$(inherited)"
        - "@executable_path/../Frameworks"
        - "@executable_path/../../../../Frameworks"
    entitlements:
      path: Entitlements/FinderSyncExtension.entitlements
    info:
      path: FinderSyncExtension/Info.plist
      properties:
        CFBundleDisplayName: SwiftSweep Finder Extension
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.FinderSync
          NSExtensionPrincipalClass: "$(PRODUCT_MODULE_NAME).FinderSync"
        LSMinimumSystemVersion: "13.0"

schemes:
  SwiftSweepMAS:
    build:
      targets:
        SwiftSweepMAS: all
        FinderSyncExtension: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
